questions = [
    {
        "id": 1,
        "en": "What does a red traffic light mean?",
        "fa": "چراغ قرمز به چه معناست؟",
        "de": "Was bedeutet eine rote Ampel?",
        "options": {
            "en": ["Stop", "Go", "Speed up"],
            "fa": ["توقف", "برو", "سرعت بگیر"],
            "de": ["Stopp", "Fahren", "Beschleunigen"],
        },
        "correct": 0,
    },
    {
        "id": 2,
        "en": "What should you do at a stop sign?",
        "fa": "در مقابل تابلوی ایست چه کار باید بکنید؟",
        "de": "Was sollten Sie an einem Stoppschild tun?",
        "options": {
            "en": ["Slow down only", "Stop fully", "Honk and go"],
            "fa": ["فقط آهسته شو", "کاملاً بایست", "بوق بزن و برو"],
            "de": ["Nur langsamer fahren", "Vollständig anhalten", "Hupen und weiterfahren"],
        },
        "correct": 1,
    },
    {
        "id": 3,
        "en": "What is the basic speed limit outside a city, town or village in Alberta?",
        "fa": "محدودیت سرعت پایه در خارج از شهر، شهرک یا روستا در آلبرتا چقدر است؟",
        "de": "Wie hoch ist die grundsätzliche Geschwindigkeitsbegrenzung außerhalb einer Stadt oder eines Dorfes in Alberta?",
        "options": {
            "en": ["100 km/h", "80 km/h", "120 km/h"],
            "fa": ["۱۰۰ کیلومتر بر ساعت", "۸۰ کیلومتر بر ساعت", "۱۲۰ کیلومتر بر ساعت"],
            "de": ["100 km/h", "80 km/h", "120 km/h"],
        },
        "correct": 0,
    },
    {
        "id": 4,
        "en": "What does a solid white line between driving lanes in an urban area mean?",
        "fa": "خط سفید ممتد بین خطوط رانندگی در منطقه شهری به چه معناست؟",
        "de": "Was bedeutet eine durchgezogene weiße Linie zwischen Fahrspuren in einem Stadtgebiet?",
        "options": {
            "en": ["You must drive faster", "Parking is allowed", "Lane changing is not permitted"],
            "fa": ["باید سریع‌تر برانید", "پارک مجاز است", "تغییر خط مجاز نیست"],
            "de": ["Sie müssen schneller fahren", "Parken ist erlaubt", "Spurwechsel ist nicht erlaubt"],
        },
        "correct": 2,
    },
    {
        "id": 5,
        "en": "When you approach a flashing red traffic light, what must you do?",
        "fa": "وقتی به چراغ قرمز چشمک‌زن نزدیک می‌شوید، چه باید بکنید؟",
        "de": "Was müssen Sie tun, wenn Sie sich einer blinkenden roten Ampel nähern?",
        "options": {
            "en": ["Slow down and continue", "Come to a complete stop and go only when safe", "Honk and go"],
            "fa": ["آهسته شوید و ادامه دهید", "کاملاً بایستید و فقط وقتی ایمن است بروید", "بوق بزنید و بروید"],
            "de": ["Langsamer werden und weiterfahren", "Vollständig anhalten und nur bei Sicherheit weiterfahren", "Hupen und weiterfahren"],
        },
        "correct": 1,
    },
    {
        "id": 6,
        "en": "How far from a fire hydrant must you park at minimum?",
        "fa": "حداقل فاصله پارک از شیر آتش‌نشانی چقدر است؟",
        "de": "Wie weit müssen Sie mindestens von einem Hydranten entfernt parken?",
        "options": {
            "en": ["1 meter", "15 meters", "5 meters"],
            "fa": ["۱ متر", "۱۵ متر", "۵ متر"],
            "de": ["1 Meter", "15 Meter", "5 Meter"],
        },
        "correct": 2,
    },
    {
        "id": 7,
        "en": "Does Alberta law require you to wear a seat belt?",
        "fa": "آیا قانون آلبرتا استفاده از کمربند ایمنی را الزامی می‌کند؟",
        "de": "Schreibt das Gesetz in Alberta das Anlegen des Sicherheitsgurts vor?",
        "options": {
            "en": ["Yes, you must wear it properly at all times", "Only on highways", "Only if you are under 18"],
            "fa": ["بله، باید همیشه درست بسته شود", "فقط در بزرگراه", "فقط اگر زیر ۱۸ سال باشید"],
            "de": ["Ja, Sie müssen ihn jederzeit richtig anlegen", "Nur auf Autobahnen", "Nur wenn Sie unter 18 sind"],
        },
        "correct": 0,
    },
    {
        "id": 8,
        "en": "When you are driving behind another vehicle at night, when must you dim your headlights?",
        "fa": "وقتی شب پشت خودروی دیگری رانندگی می‌کنید، در چه فاصله‌ای باید نور چراغ‌ها را پایین بیاورید؟",
        "de": "Wann müssen Sie nachts abblenden, wenn Sie hinter einem anderen Fahrzeug fahren?",
        "options": {
            "en": ["Within 50 meters", "Within 150 meters", "Within 500 meters"],
            "fa": ["کمتر از ۵۰ متر", "کمتر از ۱۵۰ متر", "کمتر از ۵۰۰ متر"],
            "de": ["Innerhalb von 50 Metern", "Innerhalb von 150 Metern", "Innerhalb von 500 Metern"],
        },
        "correct": 1,
    },
    {
        "id": 9,
        "en": "What should you do at a steady yellow traffic light?",
        "fa": "در چراغ زرد ثابت چه باید بکنید؟",
        "de": "Was sollten Sie bei einer gelben Ampel (Dauerlicht) tun?",
        "options": {
            "en": ["Speed up to pass the light", "Stop in the middle of the intersection", "Stop before the intersection, unless you cannot stop safely"],
            "fa": ["سرعت بگیرید تا از چراغ رد شوید", "وسط تقاطع بایستید", "قبل از تقاطع بایستید، مگر اینکه توقف ایمن ممکن نباشد"],
            "de": ["Beschleunigen, um noch durchzukommen", "Mitten auf der Kreuzung anhalten", "Vor der Kreuzung anhalten, außer wenn sicheres Anhalten nicht möglich ist"],
        },
        "correct": 2,
    },
    {
        "id": 10,
        "en": "In urban areas, how far ahead should you scan the road?",
        "fa": "در مناطق شهری، چقدر جلوتر از خودرو را باید زیر نظر داشته باشید؟",
        "de": "Wie weit voraus sollten Sie in der Stadt die Straße beobachten?",
        "options": {
            "en": ["12–15 seconds", "2–3 seconds", "1 minute"],
            "fa": ["۱۲ تا ۱۵ ثانیه", "۲ تا ۳ ثانیه", "۱ دقیقه"],
            "de": ["12–15 Sekunden", "2–3 Sekunden", "1 Minute"],
        },
        "correct": 0,
    },
    {
        "id": 11,
        "en": "What blood alcohol level is allowed for a driver in the GDL program?",
        "fa": "برای راننده‌ای که در برنامه گواهینامه مرحله‌ای (GDL) است، چه مقدار الکل در خون مجاز است؟",
        "de": "Welcher Blutalkoholwert ist für Fahrer im GDL-Programm erlaubt?",
        "options": {
            "en": ["0.05", "Zero", "0.08"],
            "fa": ["۰٫۰۵", "صفر", "۰٫۰۸"],
            "de": ["0,05", "Null", "0,08"],
        },
        "correct": 1,
    },
    {
        "id": 12,
        "en": "When are school zone speed limits in effect?",
        "fa": "محدودیت سرعت منطقه مدرسه چه زمانی اجرا می‌شود؟",
        "de": "Wann gilt die Geschwindigkeitsbegrenzung in Schulzonen?",
        "options": {
            "en": ["Every day, 24 hours", "Only on weekends", "On school days, 8 am to 4 pm"],
            "fa": ["هر روز، ۲۴ ساعت", "فقط آخر هفته‌ها", "در روزهای مدرسه، از ۸ صبح تا ۴ عصر"],
            "de": ["Jeden Tag, 24 Stunden", "Nur am Wochenende", "An Schultagen von 8 bis 16 Uhr"],
        },
        "correct": 2,
    },
    {
        "id": 13,
        "en": "When are playground zone speed limits in effect?",
        "fa": "محدودیت سرعت منطقه زمین بازی چه زمانی اجرا می‌شود؟",
        "de": "Wann gilt die Geschwindigkeitsbegrenzung in Spielplatzzonen?",
        "options": {
            "en": ["Every day, 8:30 am to 1 hour after sunset", "Only on school days", "Only at night"],
            "fa": ["هر روز از ۸:۳۰ صبح تا یک ساعت بعد از غروب", "فقط در روزهای مدرسه", "فقط شب‌ها"],
            "de": ["Jeden Tag von 8:30 Uhr bis 1 Stunde nach Sonnenuntergang", "Nur an Schultagen", "Nur nachts"],
        },
        "correct": 0,
    },
    {
        "id": 14,
        "en": "How far must you stay behind an emergency vehicle with its lights or siren on?",
        "fa": "وقتی چراغ یا آژیر خودروی امدادی روشن است، چه فاصله‌ای باید پشت آن بمانید؟",
        "de": "Welchen Abstand müssen Sie zu einem Einsatzfahrzeug mit Blaulicht oder Sirene halten?",
        "options": {
            "en": ["20 meters", "50 meters", "150 meters"],
            "fa": ["۲۰ متر", "۵۰ متر", "۱۵۰ متر"],
            "de": ["20 Meter", "50 Meter", "150 Meter"],
        },
        "correct": 2,
    },
    {
        "id": 15,
        "en": "What is hydroplaning?",
        "fa": "هیدروپلنینگ (آب‌زدگی) چیست؟",
        "de": "Was ist Aquaplaning?",
        "options": {
            "en": ["Driving too fast on a dry road", "Losing control because a thin layer of water is between the tires and the road", "A way of parking"],
            "fa": ["رانندگی خیلی سریع در جاده خشک", "از دست دادن کنترل به دلیل لایه نازک آب بین لاستیک و جاده", "نوعی پارک کردن"],
            "de": ["Zu schnelles Fahren auf trockener Straße", "Kontrollverlust durch eine dünne Wasserschicht zwischen Reifen und Straße", "Eine Art zu parken"],
        },
        "correct": 1,
    },
    {
        "id": 16,
        "en": "What must you do when a school bus has its red lights flashing?",
        "fa": "وقتی چراغ‌های قرمز اتوبوس مدرسه چشمک می‌زنند، چه باید بکنید؟",
        "de": "Was müssen Sie tun, wenn ein Schulbus rote Warnlichter blinken lässt?",
        "options": {
            "en": ["Do not pass the bus", "Pass it slowly on the left", "Honk and pass"],
            "fa": ["از اتوبوس سبقت نگیرید", "آرام از سمت چپ سبقت بگیرید", "بوق بزنید و سبقت بگیرید"],
            "de": ["Den Bus nicht überholen", "Langsam links überholen", "Hupen und überholen"],
        },
        "correct": 0,
    },
    {
        "id": 17,
        "en": "A railway crossing has flashing red lights and a bell. Where must you stop?",
        "fa": "در تقاطع راه‌آهن که چراغ قرمز چشمک‌زن و زنگ دارد، کجا باید بایستید؟",
        "de": "An einem Bahnübergang blinken rote Lichter und eine Glocke läutet. Wo müssen Sie anhalten?",
        "options": {
            "en": ["Right on the tracks", "1 meter from the nearest rail", "At least 5 meters from the nearest rail"],
            "fa": ["درست روی ریل", "۱ متر از نزدیک‌ترین ریل", "حداقل ۵ متر از نزدیک‌ترین ریل"],
            "de": ["Direkt auf den Gleisen", "1 Meter vor der nächsten Schiene", "Mindestens 5 Meter vor der nächsten Schiene"],
        },
        "correct": 2,
    },
    {
        "id": 18,
        "en": "With a Class 7 learner's licence, when are you not allowed to drive?",
        "fa": "با گواهینامه آموزشی کلاس ۷، چه زمانی اجازه رانندگی ندارید؟",
        "de": "Wann dürfen Sie mit einem Class-7-Lernführerschein nicht fahren?",
        "options": {
            "en": ["Between midnight and 5 am", "Between noon and 5 pm", "On weekends"],
            "fa": ["بین نیمه‌شب تا ۵ صبح", "بین ظهر تا ۵ عصر", "آخر هفته‌ها"],
            "de": ["Zwischen Mitternacht und 5 Uhr morgens", "Zwischen 12 und 17 Uhr", "Am Wochenende"],
        },
        "correct": 0,
    },
    {
        "id": 19,
        "en": "Under Alberta rules, what is 'night time'?",
        "fa": "طبق قوانین آلبرتا، «شب» یعنی چه زمانی؟",
        "de": "Was gilt nach den Regeln in Alberta als „Nacht“?",
        "options": {
            "en": ["From sunset to sunrise", "From 1 hour after sunset to 1 hour before sunrise", "From 10 pm to 6 am"],
            "fa": ["از غروب تا طلوع آفتاب", "از یک ساعت بعد از غروب تا یک ساعت قبل از طلوع", "از ۱۰ شب تا ۶ صبح"],
            "de": ["Von Sonnenuntergang bis Sonnenaufgang", "Von 1 Stunde nach Sonnenuntergang bis 1 Stunde vor Sonnenaufgang", "Von 22 bis 6 Uhr"],
        },
        "correct": 1,
    },
    {
        "id": 20,
        "en": "A Class 7 (GDL) driver is suspended after how many demerit points?",
        "fa": "راننده کلاس ۷ (GDL) با چند امتیاز منفی تعلیق می‌شود؟",
        "de": "Ab wie vielen Strafpunkten wird ein Class-7-Fahrer (GDL) gesperrt?",
        "options": {
            "en": ["15 points", "4 points", "8 points"],
            "fa": ["۱۵ امتیاز", "۴ امتیاز", "۸ امتیاز"],
            "de": ["15 Punkte", "4 Punkte", "8 Punkte"],
        },
        "correct": 2,
    },
    {
        "id": 21,
        "en": "A fully licensed driver is suspended after how many demerit points?",
        "fa": "راننده با گواهینامه کامل با چند امتیاز منفی تعلیق می‌شود؟",
        "de": "Ab wie vielen Strafpunkten wird ein Fahrer mit voller Fahrerlaubnis gesperrt?",
        "options": {
            "en": ["15 points", "8 points", "20 points"],
            "fa": ["۱۵ امتیاز", "۸ امتیاز", "۲۰ امتیاز"],
            "de": ["15 Punkte", "8 Punkte", "20 Punkte"],
        },
        "correct": 0,
    },
    {
        "id": 22,
        "en": "When you enter a traffic circle, who must you yield to?",
        "fa": "هنگام ورود به میدان، باید به چه کسی حق تقدم بدهید؟",
        "de": "Wem müssen Sie beim Einfahren in einen Kreisverkehr Vorfahrt gewähren?",
        "options": {
            "en": ["Nobody", "Vehicles already in the traffic circle", "Vehicles behind you"],
            "fa": ["به هیچ‌کس", "به خودروهایی که داخل میدان هستند", "به خودروهای پشت سر"],
            "de": ["Niemandem", "Fahrzeugen, die schon im Kreisverkehr sind", "Fahrzeugen hinter Ihnen"],
        },
        "correct": 1,
    },
    {
        "id": 23,
        "en": "If your car starts to skid, what should you do?",
        "fa": "اگر خودرو شروع به لغزیدن کرد، چه باید بکنید؟",
        "de": "Was sollten Sie tun, wenn Ihr Auto ins Schleudern kommt?",
        "options": {
            "en": ["Brake hard and turn the wheel quickly", "Take your hands off the wheel", "Steer in the direction you want to go"],
            "fa": ["محکم ترمز کنید و فرمان را سریع بچرخانید", "دست‌هایتان را از فرمان بردارید", "فرمان را به سمتی که می‌خواهید بروید بچرخانید"],
            "de": ["Stark bremsen und schnell lenken", "Die Hände vom Lenkrad nehmen", "In die Richtung lenken, in die Sie fahren möchten"],
        },
        "correct": 2,
    },
    {
        "id": 24,
        "en": "Which headlights should you use in fog, smoke, or snow?",
        "fa": "در مه، دود یا برف از کدام چراغ‌ها استفاده کنید؟",
        "de": "Welches Licht sollten Sie bei Nebel, Rauch oder Schnee benutzen?",
        "options": {
            "en": ["Low beam", "High beam", "No headlights"],
            "fa": ["نور پایین", "نور بالا", "بدون چراغ"],
            "de": ["Abblendlicht", "Fernlicht", "Kein Licht"],
        },
        "correct": 0,
    },
    {
        "id": 25,
        "en": "What does 'shoulder checking' mean?",
        "fa": "«شانه‌چک» (نگاه از روی شانه) یعنی چه؟",
        "de": "Was bedeutet „Schulterblick“?",
        "options": {
            "en": ["Checking your mirrors only", "Looking quickly toward your blind spot in the direction you want to move", "Checking the road shoulder for parking"],
            "fa": ["فقط نگاه کردن به آینه‌ها", "نگاه سریع به نقطه کور در جهتی که می‌خواهید حرکت کنید", "بررسی شانه جاده برای پارک"],
            "de": ["Nur in die Spiegel schauen", "Kurzer Blick in den toten Winkel in die Richtung, in die Sie fahren möchten", "Den Seitenstreifen zum Parken prüfen"],
        },
        "correct": 1,
    },
    {
        "id": 26,
        "en": "Your right tires go off the paved part of the road. What should you do?",
        "fa": "چرخ‌های سمت راست شما از قسمت آسفالت جاده خارج می‌شوند. چه کار باید بکنید؟",
        "de": "Ihre rechten Reifen kommen von der asphaltierten Fahrbahn ab. Was sollten Sie tun?",
        "options": {
            "en": ["Brake hard and turn back quickly", "Hold the wheel firmly, ease off the gas, and return gradually", "Speed up and turn sharply back"],
            "fa": ["محکم ترمز کنید و سریع برگردید", "فرمان را محکم بگیرید، پا را از گاز بردارید و به تدریج برگردید", "سرعت بگیرید و تند برگردید"],
            "de": ["Stark bremsen und schnell zurücklenken", "Lenkrad fest halten, vom Gas gehen und langsam zurückkehren", "Beschleunigen und scharf zurücklenken"],
        },
        "correct": 1,
    },
    {
        "id": 27,
        "en": "What is a deceleration lane?",
        "fa": "خط کاهش سرعت چیست؟",
        "de": "Was ist ein Verzögerungsstreifen?",
        "options": {
            "en": ["A lane for passing slow vehicles", "A lane for parking", "A lane where vehicles slow down when exiting a highway"],
            "fa": ["خطی برای سبقت از وسایل نقلیه کند", "خطی برای پارک", "خطی که خودروها هنگام خروج از بزرگراه در آن سرعت کم می‌کنند"],
            "de": ["Ein Streifen zum Überholen langsamer Fahrzeuge", "Ein Streifen zum Parken", "Ein Streifen, auf dem Fahrzeuge beim Verlassen der Autobahn langsamer werden"],
        },
        "correct": 2,
    },
    {
        "id": 28,
        "en": "What must you do when exiting a parking lot onto a road?",
        "fa": "هنگام خروج از پارکینگ به جاده چه کاری باید انجام دهید؟",
        "de": "Was müssen Sie tun, wenn Sie einen Parkplatz verlassen und auf die Straße fahren?",
        "options": {
            "en": ["Come to a complete stop", "Slow down and merge", "Honk and drive out"],
            "fa": ["کاملاً توقف کنید", "سرعت را کم کنید و وارد شوید", "بوق بزنید و خارج شوید"],
            "de": ["Vollständig anhalten", "Langsamer werden und einfädeln", "Hupen und hinausfahren"],
        },
        "correct": 0,
    },
    {
        "id": 29,
        "en": "What is an uncontrolled intersection?",
        "fa": "تقاطع بدون کنترل چیست؟",
        "de": "Was ist eine ungeregelte Kreuzung?",
        "options": {
            "en": ["An intersection with a police officer", "An intersection with traffic lights", "An intersection with no traffic signs or signals"],
            "fa": ["تقاطعی با مأمور پلیس", "تقاطعی با چراغ راهنمایی", "تقاطعی بدون تابلو یا چراغ راهنمایی"],
            "de": ["Eine Kreuzung mit einem Polizisten", "Eine Kreuzung mit Ampeln", "Eine Kreuzung ohne Verkehrszeichen oder Ampeln"],
        },
        "correct": 2,
    },
    {
        "id": 30,
        "en": "When parking uphill on a two-way road with a curb, where should your front wheels point?",
        "fa": "هنگام پارک در سربالایی در جاده دوطرفه با جدول، چرخ‌های جلو باید به کدام سمت باشند؟",
        "de": "Wohin sollten die Vorderräder zeigen, wenn Sie bergauf an einer Straße mit Bordstein parken?",
        "options": {
            "en": ["Toward the curb (right)", "Away from the curb (left)", "Straight ahead"],
            "fa": ["به سمت جدول (راست)", "دور از جدول (چپ)", "مستقیم"],
            "de": ["Zum Bordstein (rechts)", "Weg vom Bordstein (links)", "Geradeaus"],
        },
        "correct": 1,
    },
    {
        "id": 31,
        "en": "When parking downhill on a two-way road with a curb, where should your front wheels point?",
        "fa": "هنگام پارک در سرازیری در جاده دوطرفه با جدول، چرخ‌های جلو باید به کدام سمت باشند؟",
        "de": "Wohin sollten die Vorderräder zeigen, wenn Sie bergab an einer Straße mit Bordstein parken?",
        "options": {
            "en": ["Toward the curb", "Away from the curb", "Straight ahead"],
            "fa": ["به سمت جدول", "دور از جدول", "مستقیم"],
            "de": ["Zum Bordstein", "Weg vom Bordstein", "Geradeaus"],
        },
        "correct": 0,
    },
    {
        "id": 32,
        "en": "On a two-lane highway, how should you pass a vehicle going in the same direction?",
        "fa": "در بزرگراه دوخطه، چگونه باید از خودرویی که در همان جهت حرکت می‌کند سبقت بگیرید؟",
        "de": "Wie überholen Sie auf einer zweispurigen Landstraße ein Fahrzeug in gleicher Richtung?",
        "options": {
            "en": ["On the right shoulder", "On either side", "On the left, when it is safe"],
            "fa": ["از شانه سمت راست", "از هر دو طرف", "از سمت چپ، وقتی امن است"],
            "de": ["Auf dem rechten Seitenstreifen", "Auf beiden Seiten", "Links, wenn es sicher ist"],
        },
        "correct": 2,
    },
    {
        "id": 33,
        "en": "You are in the right lane of a highway and a vehicle is merging from the acceleration lane. What should you do?",
        "fa": "در خط راست بزرگراه هستید و خودرویی از خط افزایش سرعت وارد می‌شود. چه کار باید بکنید؟",
        "de": "Sie fahren auf der rechten Spur der Autobahn und ein Fahrzeug fädelt vom Beschleunigungsstreifen ein. Was tun Sie?",
        "options": {
            "en": ["Speed up so it cannot merge", "Move to the left lane if safe, or adjust your speed", "Stop on the highway"],
            "fa": ["سرعت بگیرید تا نتواند وارد شود", "اگر امن است به خط چپ بروید یا سرعت خود را تنظیم کنید", "در بزرگراه توقف کنید"],
            "de": ["Beschleunigen, damit es nicht einfädeln kann", "Wenn sicher, nach links wechseln oder die Geschwindigkeit anpassen", "Auf der Autobahn anhalten"],
        },
        "correct": 1,
    },
    {
        "id": 34,
        "en": "On a two-way road, another vehicle is passing you. What should you do?",
        "fa": "در جاده دوطرفه، خودروی دیگری در حال سبقت از شماست. چه کار باید بکنید؟",
        "de": "Auf einer Straße mit Gegenverkehr überholt Sie ein anderes Fahrzeug. Was sollten Sie tun?",
        "options": {
            "en": ["Stay in your lane and move to the right part of it", "Speed up", "Move to the left part of your lane"],
            "fa": ["در خط خود بمانید و به قسمت راست آن بروید", "سرعت بگیرید", "به قسمت چپ خط خود بروید"],
            "de": ["In der Spur bleiben und nach rechts in der Spur fahren", "Beschleunigen", "Nach links in der Spur fahren"],
        },
        "correct": 0,
    },
    {
        "id": 35,
        "en": "Who must report a medical condition that may affect your ability to drive?",
        "fa": "چه کسی باید بیماری‌ای را که ممکن است بر توانایی رانندگی شما اثر بگذارد گزارش دهد؟",
        "de": "Wer muss eine Krankheit melden, die Ihre Fahrtüchtigkeit beeinträchtigen kann?",
        "options": {
            "en": ["Your doctor only", "You, the driver", "No one needs to report it"],
            "fa": ["فقط پزشک شما", "شما، یعنی راننده", "نیازی به گزارش نیست"],
            "de": ["Nur Ihr Arzt", "Sie selbst als Fahrer", "Niemand muss es melden"],
        },
        "correct": 1,
    },
    {
        "id": 36,
        "en": "Under the GDL program, what is the minimum time you must spend as a probationary driver?",
        "fa": "در برنامه GDL، حداقل مدتی که باید به عنوان راننده آزمایشی بگذرانید چقدر است؟",
        "de": "Wie lange müssen Sie im GDL-Programm mindestens Fahrer auf Probe sein?",
        "options": {
            "en": ["6 months", "1 year", "2 years"],
            "fa": ["۶ ماه", "۱ سال", "۲ سال"],
            "de": ["6 Monate", "1 Jahr", "2 Jahre"],
        },
        "correct": 2,
    },
    {
        "id": 37,
        "en": "What does 'overdriving your headlights' mean?",
        "fa": "«جلوتر از نور چراغ‌ها رانندگی کردن» یعنی چه؟",
        "de": "Was bedeutet es, „schneller als die Scheinwerfer“ zu fahren?",
        "options": {
            "en": ["Driving too fast to stop within the distance your headlights light up", "Using high beams in the city", "Driving with the headlights off"],
            "fa": ["آن‌قدر سریع رانندگی کنید که نتوانید در فاصله‌ای که چراغ‌ها روشن می‌کنند بایستید", "استفاده از نور بالا در شهر", "رانندگی با چراغ‌های خاموش"],
            "de": ["So schnell fahren, dass Sie nicht innerhalb der beleuchteten Strecke anhalten können", "Fernlicht in der Stadt benutzen", "Ohne Licht fahren"],
        },
        "correct": 0,
    },
    {
        "id": 38,
        "en": "Can you go over the speed limit while passing another vehicle?",
        "fa": "آیا هنگام سبقت گرفتن می‌توانید از حد مجاز سرعت بیشتر بروید؟",
        "de": "Dürfen Sie beim Überholen die Geschwindigkeitsbegrenzung überschreiten?",
        "options": {
            "en": ["Yes, up to 10 km/h", "Yes, if the road is empty", "No, never"],
            "fa": ["بله، تا ۱۰ کیلومتر بر ساعت", "بله، اگر جاده خالی باشد", "نه، هرگز"],
            "de": ["Ja, bis zu 10 km/h", "Ja, wenn die Straße leer ist", "Nein, niemals"],
        },
        "correct": 2,
    },
    {
        "id": 39,
        "en": "Who is responsible for making sure passengers aged 16 and under are properly restrained?",
        "fa": "چه کسی مسئول است که مسافران ۱۶ سال و کمتر به درستی بسته شده باشند؟",
        "de": "Wer ist dafür verantwortlich, dass Mitfahrer bis 16 Jahre richtig angeschnallt sind?",
        "options": {
            "en": ["The passenger", "The driver", "Only the parents"],
            "fa": ["خود مسافر", "راننده", "فقط والدین"],
            "de": ["Der Mitfahrer", "Der Fahrer", "Nur die Eltern"],
        },
        "correct": 1,
    },
    {
        "id": 40,
        "en": "What is threshold braking?",
        "fa": "ترمز آستانه‌ای چیست؟",
        "de": "Was ist Schwellenbremsung?",
        "options": {
            "en": ["Braking firmly to just before the wheels lock, and easing off slightly if they lock", "Pumping the brake pedal very fast", "Braking only with the parking brake"],
            "fa": ["ترمز محکم تا درست قبل از قفل شدن چرخ‌ها و کمی رها کردن اگر قفل شدند", "پمپ کردن خیلی سریع پدال ترمز", "ترمز فقط با ترمز دستی"],
            "de": ["Kräftig bremsen bis kurz vor dem Blockieren und leicht lösen, wenn die Räder blockieren", "Sehr schnell pumpend bremsen", "Nur mit der Handbremse bremsen"],
        },
        "correct": 0,
    },
    {
        "id": 41,
        "en": "On a highway, after you pass a large truck, what should you do?",
        "fa": "در بزرگراه، بعد از سبقت از یک کامیون بزرگ چه کار باید بکنید؟",
        "de": "Was sollten Sie auf der Autobahn tun, nachdem Sie einen großen Lkw überholt haben?",
        "options": {
            "en": ["Return to your lane right away", "Slow down in front of the truck", "Leave extra room before returning to your lane"],
            "fa": ["فوراً به خط خود برگردید", "جلوی کامیون سرعت کم کنید", "قبل از برگشتن به خط خود فاصله بیشتری بگذارید"],
            "de": ["Sofort auf Ihre Spur zurückkehren", "Vor dem Lkw langsamer werden", "Extra Abstand lassen, bevor Sie zurückwechseln"],
        },
        "correct": 2,
    },
    {
        "id": 42,
        "en": "In traffic, when you stop behind another vehicle, how much space should you leave?",
        "fa": "در ترافیک، وقتی پشت خودروی دیگری می‌ایستید، چقدر فاصله باید بگذارید؟",
        "de": "Wie viel Abstand sollten Sie lassen, wenn Sie im Verkehr hinter einem Fahrzeug anhalten?",
        "options": {
            "en": ["As little as possible", "Enough to move into another lane without reversing", "Exactly 1 metre"],
            "fa": ["هر چه کمتر بهتر", "به اندازه‌ای که بدون دنده عقب بتوانید به خط دیگر بروید", "دقیقاً ۱ متر"],
            "de": ["So wenig wie möglich", "Genug, um ohne Rückwärtsfahren die Spur wechseln zu können", "Genau 1 Meter"],
        },
        "correct": 1,
    },
    {
        "id": 43,
        "en": "How should you turn right at a red light?",
        "fa": "چگونه باید در چراغ قرمز به راست بپیچید؟",
        "de": "Wie biegen Sie bei Rot rechts ab?",
        "options": {
            "en": ["Check there is no sign against it, stop, look both ways, yield, then turn", "Turn without stopping if the road is clear", "Right turns on red are never allowed"],
            "fa": ["مطمئن شوید تابلوی ممنوعیت نیست، بایستید، دو طرف را نگاه کنید، حق تقدم بدهید، سپس بپیچید", "اگر جاده خالی است بدون توقف بپیچید", "پیچیدن به راست در چراغ قرمز هرگز مجاز نیست"],
            "de": ["Prüfen, dass kein Verbotsschild da ist, anhalten, schauen, Vorfahrt gewähren, dann abbiegen", "Ohne Anhalten abbiegen, wenn frei ist", "Rechtsabbiegen bei Rot ist nie erlaubt"],
        },
        "correct": 0,
    },
    {
        "id": 44,
        "en": "How should you drive through a curve on a highway?",
        "fa": "چگونه باید از یک پیچ در بزرگراه عبور کنید؟",
        "de": "Wie fahren Sie auf der Landstraße durch eine Kurve?",
        "options": {
            "en": ["Speed up before the curve", "Slow down before the curve, then gently accelerate after entering it", "Brake hard in the middle of the curve"],
            "fa": ["قبل از پیچ سرعت بگیرید", "قبل از پیچ سرعت کم کنید و بعد از ورود به پیچ به آرامی گاز بدهید", "وسط پیچ محکم ترمز کنید"],
            "de": ["Vor der Kurve beschleunigen", "Vor der Kurve langsamer werden und nach der Einfahrt sanft beschleunigen", "In der Mitte der Kurve stark bremsen"],
        },
        "correct": 1,
    },
    {
        "id": 45,
        "en": "When will a driver examiner refuse to give a road test?",
        "fa": "ممتحن رانندگی چه زمانی از برگزاری آزمون عملی خودداری می‌کند؟",
        "de": "Wann verweigert ein Prüfer die praktische Fahrprüfung?",
        "options": {
            "en": ["When the driver is nervous", "When it is raining", "When the vehicle is not mechanically safe"],
            "fa": ["وقتی راننده مضطرب است", "وقتی باران می‌بارد", "وقتی خودرو از نظر فنی ایمن نیست"],
            "de": ["Wenn der Fahrer nervös ist", "Wenn es regnet", "Wenn das Fahrzeug technisch nicht sicher ist"],
        },
        "correct": 2,
    },
    {
        "id": 46,
        "en": "When are dual turns (two lanes turning the same way) allowed at an intersection?",
        "fa": "چه زمانی گردش دوگانه (دو خط که به یک سمت می‌پیچند) در تقاطع مجاز است؟",
        "de": "Wann sind doppelte Abbiegespuren an einer Kreuzung erlaubt?",
        "options": {
            "en": ["Only when signs or road markings show it", "At every intersection", "Only at night"],
            "fa": ["فقط وقتی تابلو یا خط‌کشی آن را نشان دهد", "در همه تقاطع‌ها", "فقط در شب"],
            "de": ["Nur wenn Schilder oder Markierungen es anzeigen", "An jeder Kreuzung", "Nur nachts"],
        },
        "correct": 0,
    },
    {
        "id": 47,
        "en": "How do you know that a school zone or playground zone has ended?",
        "fa": "از کجا می‌فهمید که منطقه مدرسه یا زمین بازی تمام شده است؟",
        "de": "Woran erkennen Sie das Ende einer Schul- oder Spielplatzzone?",
        "options": {
            "en": ["When you pass the school building", "After 500 metres", "A sign shows a higher speed limit"],
            "fa": ["وقتی از ساختمان مدرسه رد می‌شوید", "بعد از ۵۰۰ متر", "تابلویی محدودیت سرعت بالاتر را نشان می‌دهد"],
            "de": ["Wenn Sie am Schulgebäude vorbei sind", "Nach 500 Metern", "Ein Schild zeigt eine höhere Geschwindigkeit"],
        },
        "correct": 2,
    },
    {
        "id": 48,
        "en": "What does a posted speed limit show?",
        "fa": "تابلوی محدودیت سرعت چه چیزی را نشان می‌دهد؟",
        "de": "Was zeigt eine Geschwindigkeitsbegrenzung an?",
        "options": {
            "en": ["The minimum speed", "The maximum speed in good conditions", "The speed for bad weather"],
            "fa": ["حداقل سرعت", "حداکثر سرعت در شرایط خوب", "سرعت مخصوص هوای بد"],
            "de": ["Die Mindestgeschwindigkeit", "Die Höchstgeschwindigkeit bei guten Bedingungen", "Die Geschwindigkeit bei schlechtem Wetter"],
        },
        "correct": 1,
    },
    {
        "id": 49,
        "en": "A solid yellow line is beside a broken yellow line. What does it mean?",
        "fa": "یک خط زرد ممتد کنار یک خط زرد منقطع است. یعنی چه؟",
        "de": "Eine durchgezogene gelbe Linie liegt neben einer unterbrochenen gelben Linie. Was bedeutet das?",
        "options": {
            "en": ["You may pass only from the side with the broken line", "Nobody may pass", "Everybody may pass"],
            "fa": ["فقط از سمتی که خط منقطع است می‌توان سبقت گرفت", "هیچ‌کس نمی‌تواند سبقت بگیرد", "همه می‌توانند سبقت بگیرند"],
            "de": ["Nur von der Seite mit der unterbrochenen Linie darf überholt werden", "Niemand darf überholen", "Alle dürfen überholen"],
        },
        "correct": 0,
    },
    {
        "id": 50,
        "en": "What is the difference between yellow and white road lines?",
        "fa": "تفاوت خطوط زرد و سفید جاده چیست؟",
        "de": "Was ist der Unterschied zwischen gelben und weißen Fahrbahnlinien?",
        "options": {
            "en": ["Yellow is for bikes, white is for cars", "They mean the same thing", "Yellow separates opposite directions; white separates the same direction"],
            "fa": ["زرد برای دوچرخه، سفید برای خودرو", "هر دو یک معنی دارند", "زرد جهت‌های مخالف را جدا می‌کند، سفید جهت یکسان را"],
            "de": ["Gelb für Fahrräder, Weiß für Autos", "Beide bedeuten dasselbe", "Gelb trennt Gegenrichtungen, Weiß trennt gleiche Richtung"],
        },
        "correct": 2,
    },
    {
        "id": 51,
        "en": "A funeral procession is crossing an intersection. What should you do?",
        "fa": "یک دسته تشییع جنازه در حال عبور از تقاطع است. چه کار باید بکنید؟",
        "de": "Ein Trauerzug überquert eine Kreuzung. Was sollten Sie tun?",
        "options": {
            "en": ["Drive through the gaps", "Yield and do not cut through it", "Honk so they let you pass"],
            "fa": ["از فاصله‌ها رد شوید", "حق تقدم بدهید و از میان آن عبور نکنید", "بوق بزنید تا راه بدهند"],
            "de": ["Durch die Lücken fahren", "Vorfahrt gewähren und den Zug nicht durchbrechen", "Hupen, damit sie Sie durchlassen"],
        },
        "correct": 1,
    },
    {
        "id": 52,
        "en": "The traffic light shows a green right-turn arrow and a red light. What can you do?",
        "fa": "چراغ راهنمایی فلش سبز گردش به راست و چراغ قرمز را نشان می‌دهد. چه کاری می‌توانید بکنید؟",
        "de": "Die Ampel zeigt einen grünen Rechtspfeil und Rot. Was dürfen Sie tun?",
        "options": {
            "en": ["Go in the direction of the arrow without stopping, yielding to pedestrians", "Stop and wait for a full green light", "Go straight through"],
            "fa": ["بدون توقف در جهت فلش بروید و به عابران حق تقدم بدهید", "بایستید و منتظر چراغ سبز کامل بمانید", "مستقیم بروید"],
            "de": ["Ohne Anhalten in Pfeilrichtung fahren und Fußgängern Vorrang geben", "Anhalten und auf volles Grün warten", "Geradeaus fahren"],
        },
        "correct": 0,
    },
    {
        "id": 53,
        "en": "What does a red X above a lane mean?",
        "fa": "علامت X قرمز بالای یک خط به چه معناست؟",
        "de": "Was bedeutet ein rotes X über einer Fahrspur?",
        "options": {
            "en": ["Use it for passing only", "Drive slowly in it", "Do not drive in that lane"],
            "fa": ["فقط برای سبقت استفاده کنید", "در آن آهسته برانید", "در آن خط رانندگی نکنید"],
            "de": ["Nur zum Überholen benutzen", "Darauf langsam fahren", "Diese Spur nicht befahren"],
        },
        "correct": 2,
    },
    {
        "id": 54,
        "en": "Which lane should you use to turn left from a one-way road?",
        "fa": "برای گردش به چپ از یک خیابان یک‌طرفه از کدام خط باید استفاده کنید؟",
        "de": "Welche Spur benutzen Sie, um aus einer Einbahnstraße links abzubiegen?",
        "options": {
            "en": ["The right lane", "The lane closest to the left curb", "Any lane"],
            "fa": ["خط راست", "نزدیک‌ترین خط به جدول سمت چپ", "هر خطی"],
            "de": ["Die rechte Spur", "Die Spur am nächsten zum linken Bordstein", "Jede Spur"],
        },
        "correct": 1,
    },
    {
        "id": 55,
        "en": "Is it safe to pass a long truck while it is turning?",
        "fa": "آیا سبقت گرفتن از یک کامیون بلند در حال پیچیدن امن است؟",
        "de": "Ist es sicher, einen langen Lkw beim Abbiegen zu überholen?",
        "options": {
            "en": ["No, its overhang can block the lanes during the turn", "Yes, on the right side", "Yes, if you honk first"],
            "fa": ["نه، بخش بیرون‌زده آن ممکن است هنگام پیچیدن خط‌ها را ببندد", "بله، از سمت راست", "بله، اگر اول بوق بزنید"],
            "de": ["Nein, der Überhang kann beim Abbiegen die Spuren blockieren", "Ja, auf der rechten Seite", "Ja, wenn Sie vorher hupen"],
        },
        "correct": 0,
    },
    {
        "id": 56,
        "en": "You see a 'passing lane ahead' sign. What should the driver of a slow vehicle do?",
        "fa": "تابلوی «خط سبقت در پیش رو» را می‌بینید. راننده خودروی کند چه کار باید بکند؟",
        "de": "Sie sehen ein Schild „Überholspur voraus“. Was sollte der Fahrer eines langsamen Fahrzeugs tun?",
        "options": {
            "en": ["Speed up", "Move into the right lane when safe", "Stop on the shoulder"],
            "fa": ["سرعت بگیرد", "وقتی امن است به خط راست برود", "روی شانه جاده توقف کند"],
            "de": ["Beschleunigen", "Wenn sicher, auf die rechte Spur wechseln", "Auf dem Seitenstreifen anhalten"],
        },
        "correct": 1,
    },
    {
        "id": 57,
        "en": "At a stop sign with a marked crosswalk, where must you stop?",
        "fa": "در تابلوی ایست با خط عابر پیاده، کجا باید توقف کنید؟",
        "de": "Wo müssen Sie an einem Stoppschild mit markiertem Fußgängerüberweg anhalten?",
        "options": {
            "en": ["After the crosswalk", "In the middle of the crosswalk", "Before the crosswalk or stop line"],
            "fa": ["بعد از خط عابر", "وسط خط عابر", "قبل از خط عابر یا خط ایست"],
            "de": ["Nach dem Überweg", "Mitten auf dem Überweg", "Vor dem Überweg oder der Haltelinie"],
        },
        "correct": 2,
    },
    {
        "id": 58,
        "en": "Where should your head restraint be?",
        "fa": "پشت‌سری صندلی شما باید در چه ارتفاعی باشد؟",
        "de": "Wie sollte Ihre Kopfstütze eingestellt sein?",
        "options": {
            "en": ["Its centre level with the top of your ears", "At your neck", "As low as possible"],
            "fa": ["مرکز آن هم‌سطح بالای گوش‌های شما", "در سطح گردن", "تا جای ممکن پایین"],
            "de": ["Die Mitte auf Höhe der Oberkante Ihrer Ohren", "Auf Höhe des Nackens", "So tief wie möglich"],
        },
        "correct": 0,
    },
    {
        "id": 59,
        "en": "A vehicle has stopped to let a pedestrian cross. You are behind it. What should you do?",
        "fa": "خودرویی برای عبور عابر پیاده ایستاده و شما پشت آن هستید. چه کار باید بکنید؟",
        "de": "Ein Fahrzeug hält an, um einen Fußgänger queren zu lassen. Sie sind dahinter. Was tun Sie?",
        "options": {
            "en": ["Pass it on the left", "Pass it on the right", "Do not pass it; that is illegal"],
            "fa": ["از سمت چپ از آن سبقت بگیرید", "از سمت راست از آن سبقت بگیرید", "سبقت نگیرید؛ غیرقانونی است"],
            "de": ["Links überholen", "Rechts überholen", "Nicht überholen, das ist verboten"],
        },
        "correct": 2,
    },
    {
        "id": 60,
        "en": "A pedestrian at a crosswalk holds an arm out at a right angle. What should you do?",
        "fa": "عابری کنار خط عابر دستش را با زاویه قائم بالا گرفته است. چه کار باید بکنید؟",
        "de": "Ein Fußgänger am Überweg streckt den Arm im rechten Winkel aus. Was tun Sie?",
        "options": {
            "en": ["Honk and keep driving", "Come to a complete stop", "Slow down and pass"],
            "fa": ["بوق بزنید و ادامه دهید", "کاملاً توقف کنید", "سرعت کم کنید و رد شوید"],
            "de": ["Hupen und weiterfahren", "Vollständig anhalten", "Langsamer werden und vorbeifahren"],
        },
        "correct": 1,
    },
    {
        "id": 61,
        "en": "What is a weave zone on a highway?",
        "fa": "منطقه درهم‌رفت (Weave zone) در بزرگراه چیست؟",
        "de": "Was ist ein Verflechtungsbereich auf der Autobahn?",
        "options": {
            "en": ["A place where entrance and exit lanes are close together", "A lane only for bikes", "A construction zone"],
            "fa": ["جایی که خط ورود و خروج به هم نزدیک‌اند", "خطی فقط برای دوچرخه", "منطقه ساخت و ساز"],
            "de": ["Ein Bereich, in dem Ein- und Ausfahrspuren nah beieinander liegen", "Eine Spur nur für Fahrräder", "Eine Baustelle"],
        },
        "correct": 0,
    },
    {
        "id": 62,
        "en": "What causes most skids?",
        "fa": "بیشتر لغزش‌ها به چه علت است؟",
        "de": "Was verursacht die meisten Schleudervorgänge?",
        "options": {
            "en": ["Bad tires", "The weather", "Driver error"],
            "fa": ["لاستیک‌های خراب", "آب و هوا", "خطای راننده"],
            "de": ["Schlechte Reifen", "Das Wetter", "Fahrerfehler"],
        },
        "correct": 2,
    },
    {
        "id": 63,
        "en": "What must you give a police officer when asked?",
        "fa": "وقتی مأمور پلیس درخواست کند، چه چیزی باید به او بدهید؟",
        "de": "Was müssen Sie einem Polizisten auf Verlangen zeigen?",
        "options": {
            "en": ["Only your name", "Your driver's licence and proof of insurance", "Nothing"],
            "fa": ["فقط نام خود", "گواهینامه رانندگی و مدرک بیمه", "هیچ چیز"],
            "de": ["Nur Ihren Namen", "Führerschein und Versicherungsnachweis", "Nichts"],
        },
        "correct": 1,
    },
    {
        "id": 64,
        "en": "Two vehicles reach an uncontrolled intersection at about the same time. Which one must yield?",
        "fa": "دو خودرو تقریباً همزمان به یک تقاطع بدون کنترل می‌رسند. کدام باید حق تقدم بدهد؟",
        "de": "Zwei Fahrzeuge erreichen ungefähr gleichzeitig eine ungeregelte Kreuzung. Wer muss Vorfahrt gewähren?",
        "options": {
            "en": ["The vehicle on the left", "The vehicle on the right", "The faster vehicle"],
            "fa": ["خودروی سمت چپ", "خودروی سمت راست", "خودروی سریع‌تر"],
            "de": ["Das Fahrzeug links", "Das Fahrzeug rechts", "Das schnellere Fahrzeug"],
        },
        "correct": 0,
    },
    {
        "id": 65,
        "en": "A slow-moving vehicle sign must be shown on vehicles that normally travel slower than:",
        "fa": "تابلوی وسیله نقلیه کندرو باید روی وسایلی باشد که معمولاً کندتر از این سرعت حرکت می‌کنند:",
        "de": "Ein Schild für langsame Fahrzeuge muss an Fahrzeugen angebracht sein, die normalerweise langsamer fahren als:",
        "options": {
            "en": ["60 km/h", "80 km/h", "40 km/h"],
            "fa": ["۶۰ کیلومتر بر ساعت", "۸۰ کیلومتر بر ساعت", "۴۰ کیلومتر بر ساعت"],
            "de": ["60 km/h", "80 km/h", "40 km/h"],
        },
        "correct": 2,
    },
    {
        "id": 66,
        "en": "When you enter a traffic circle, who has the right of way?",
        "fa": "هنگام ورود به میدان، حق تقدم با کیست؟",
        "de": "Wer hat Vorfahrt, wenn Sie in einen Kreisverkehr einfahren?",
        "options": {
            "en": ["Vehicles entering the circle", "Vehicles already in the circle", "The biggest vehicle"],
            "fa": ["خودروهایی که وارد میدان می‌شوند", "خودروهایی که داخل میدان هستند", "بزرگ‌ترین خودرو"],
            "de": ["Fahrzeuge, die einfahren", "Fahrzeuge, die schon im Kreisverkehr sind", "Das größte Fahrzeug"],
        },
        "correct": 1,
    },
    {
        "id": 67,
        "en": "Before leaving a parallel parking spot on the right side of the road, where should you check?",
        "fa": "قبل از خروج از پارک موازی در سمت راست جاده، کجا را باید بررسی کنید؟",
        "de": "Wohin müssen Sie schauen, bevor Sie aus einer Parklücke am rechten Straßenrand ausfahren?",
        "options": {
            "en": ["To your left, with a shoulder check", "Only the right mirror", "Nowhere, if you signal"],
            "fa": ["به سمت چپ، با نگاه از روی شانه", "فقط آینه راست", "هیچ‌جا، اگر راهنما بزنید"],
            "de": ["Nach links, mit Schulterblick", "Nur in den rechten Spiegel", "Nirgends, wenn Sie blinken"],
        },
        "correct": 0,
    },
    {
        "id": 68,
        "en": "When you come to the top of a hill on a two-lane highway, what should you do?",
        "fa": "وقتی در بزرگراه دوخطه به بالای تپه می‌رسید، چه کار باید بکنید؟",
        "de": "Was sollten Sie auf einer zweispurigen Landstraße an einer Hügelkuppe tun?",
        "options": {
            "en": ["Move to the centre of the road", "Speed up", "Keep to the right part of your lane"],
            "fa": ["به وسط جاده بروید", "سرعت بگیرید", "در قسمت راست خط خود بمانید"],
            "de": ["In die Straßenmitte fahren", "Beschleunigen", "Im rechten Teil Ihrer Spur bleiben"],
        },
        "correct": 2,
    },
    {
        "id": 69,
        "en": "How should you turn left at a steady green light?",
        "fa": "در چراغ سبز ثابت چگونه باید به چپ بپیچید؟",
        "de": "Wie biegen Sie bei Dauergrün links ab?",
        "options": {
            "en": ["Turn quickly before the oncoming cars", "Turn only when it is safe, without crossing the path of oncoming vehicles", "Never turn left on a green light"],
            "fa": ["قبل از رسیدن خودروهای روبرو سریع بپیچید", "فقط وقتی امن است بپیچید، بدون قطع کردن مسیر خودروهای روبرو", "هرگز در چراغ سبز به چپ نپیچید"],
            "de": ["Schnell vor dem Gegenverkehr abbiegen", "Nur abbiegen, wenn es sicher ist, ohne den Gegenverkehr zu kreuzen", "Bei Grün nie links abbiegen"],
        },
        "correct": 1,
    },
    {
        "id": 70,
        "en": "How should you exit a two-lane traffic circle from the inside lane?",
        "fa": "چگونه باید از خط داخلی یک میدان دوخطه خارج شوید؟",
        "de": "Wie verlassen Sie einen zweispurigen Kreisverkehr von der inneren Spur?",
        "options": {
            "en": ["Signal right and use caution", "No need to signal", "Signal left"],
            "fa": ["راهنمای راست بزنید و با احتیاط خارج شوید", "نیازی به راهنما نیست", "راهنمای چپ بزنید"],
            "de": ["Rechts blinken und vorsichtig ausfahren", "Kein Blinken nötig", "Links blinken"],
        },
        "correct": 0,
    },
]
